export const backgrounds = [
  { name: "White", value: "bg-white", preview: "#ffffff" },
  { name: "Dark Gray", value: "bg-gray-100", preview: "#f3f4f6" },
  { name: "Bold Blue", value: "bg-blue-100", preview: "#dbeafe" },
  { name: "Bold Green", value: "bg-green-100", preview: "#dcfce7" },
  { name: "Bold Purple", value: "bg-purple-100", preview: "#e9d5ff" },
  { name: "Bold Pink", value: "bg-pink-100", preview: "#fce7f3" },
  { name: "Bold Yellow", value: "bg-yellow-100", preview: "#fef3c7" },
  { name: "Bold Orange", value: "bg-orange-100", preview: "#fed7aa" },
  { name: "Bold Red", value: "bg-red-100", preview: "#fee2e2" },
  { name: "Bold Indigo", value: "bg-indigo-100", preview: "#e0e7ff" },
  { name: "Bold Cyan", value: "bg-cyan-100", preview: "#cffafe" },
  { name: "Bold Teal", value: "bg-teal-100", preview: "#ccfbf1" },
  { name: "Bold Lime", value: "bg-lime-100", preview: "#ecfccb" },
  { name: "Bold Emerald", value: "bg-emerald-100", preview: "#d1fae5" },
  { name: "Bold Sky", value: "bg-sky-100", preview: "#e0f2fe" },
  { name: "Bold Violet", value: "bg-violet-100", preview: "#ede9fe" },
  { name: "Bold Fuchsia", value: "bg-fuchsia-100", preview: "#fae8ff" },
  { name: "Bold Rose", value: "bg-rose-100", preview: "#ffe4e6" },
  { name: "Bold Slate", value: "bg-slate-100", preview: "#f1f5f9" },
  { name: "Bold Zinc", value: "bg-zinc-100", preview: "#f4f4f5" },
  { name: "Bold Neutral", value: "bg-neutral-100", preview: "#f5f5f5" },
  { name: "Bold Stone", value: "bg-stone-100", preview: "#f5f5f4" },
  { name: "Ocean Wave", value: "bg-gradient-to-br from-blue-200 via-cyan-200 to-teal-200", preview: "linear-gradient(135deg, #bfdbfe, #a5f3fc, #99f6e4)" },
  { name: "Sunset", value: "bg-gradient-to-br from-orange-200 via-pink-200 to-red-200", preview: "linear-gradient(135deg, #fed7aa, #fbcfe8, #fecaca)" },
  { name: "Forest", value: "bg-gradient-to-br from-green-200 via-emerald-200 to-teal-200", preview: "linear-gradient(135deg, #bbf7d0, #a7f3d0, #99f6e4)" },
  { name: "Lavender", value: "bg-gradient-to-br from-purple-200 via-violet-200 to-pink-200", preview: "linear-gradient(135deg, #e9d5ff, #ddd6fe, #fbcfe8)" },
  { name: "Aurora", value: "bg-gradient-to-br from-cyan-200 via-blue-200 to-indigo-200", preview: "linear-gradient(135deg, #a5f3fc, #bfdbfe, #c7d2fe)" },
  { name: "Fire", value: "bg-gradient-to-br from-yellow-200 via-orange-200 to-red-200", preview: "linear-gradient(135deg, #fef3c7, #fed7aa, #fecaca)" },
  { name: "Mint", value: "bg-gradient-to-br from-green-200 via-lime-200 to-yellow-200", preview: "linear-gradient(135deg, #bbf7d0, #ecfccb, #fef3c7)" },
  { name: "Cosmic", value: "bg-gradient-to-br from-indigo-200 via-purple-200 to-pink-200", preview: "linear-gradient(135deg, #c7d2fe, #e9d5ff, #fbcfe8)" },
  { name: "Steel", value: "bg-gradient-to-br from-slate-200 via-gray-200 to-zinc-200", preview: "linear-gradient(135deg, #e2e8f0, #e5e7eb, #f4f4f5)" },
  { name: "Tropical", value: "bg-gradient-to-br from-teal-200 via-cyan-200 to-blue-200", preview: "linear-gradient(135deg, #99f6e4, #a5f3fc, #bfdbfe)" },
  { name: "Royal", value: "bg-gradient-to-br from-violet-200 via-purple-200 to-indigo-200", preview: "linear-gradient(135deg, #ddd6fe, #e9d5ff, #c7d2fe)" },
  { name: "Coral", value: "bg-gradient-to-br from-rose-200 via-pink-200 to-orange-200", preview: "linear-gradient(135deg, #fecdd3, #fbcfe8, #fed7aa)" },
]
